# FROM php:8.2-apache

# RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

FROM php:8.2-apache

# 1. Install dependensi sistem dan extension PHP
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl

# 2. Install extension PHP untuk MySQL
RUN docker-php-ext-install pdo pdo_mysql mysqli mbstring exif pcntl bcmath gd

# 3. Aktifkan Apache mod_rewrite untuk Laravel Routing
RUN a2enmod rewrite

# 4. Install Composer (Untuk install Laravel nantinya)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# 5. Beri izin akses ke user apache
RUN chown -R www-data:www-data /var/www/html